export const INSERT_CELL = 'INSERT_CELL'
export const REMOVE_CELL = 'REMOVE_CELL'
export const MOVE_CELL = 'MOVE_CELL'
export const SET_MOVED = 'SET_MOVED'
export const INC_MOVE_COUNT = 'INC_MOVE_COUNT'
export const ADD_SCORE = 'ADD_SCORE'
export const RESET_BOARD = 'RESET_BOARD'
